version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    volumes:
      - ./data_mongo:/data/db
    ports:
      - "27017:27017"